global:
  scrape_interval: 5s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # cAdvisor - Docker containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Node exporter - Linux host
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

